export const spotifyJsonSchema = {
  type: "object",
  properties: {
    // seed_artists: {
    //   type: "array",
    //   items: {
    //     type: "string",
    //   },
    //   minItems: 1,
    //   maxItems: 5,
    //   description: "最大5つのSpotifyアーティストID。",
    // },
    seed_genres: {
      type: "array",
      items: {
        type: "string",
      },
      minItems: 1,
      maxItems: 5,
      description: "最大5つのジャンル",
      enum: [
        "acoustic",
        "afrobeat",
        "alt-rock",
        "alternative",
        "ambient",
        "anime",
        "black-metal",
        "bluegrass",
        "blues",
        "bossanova",
        "brazil",
        "breakbeat",
        "british",
        "cantopop",
        "chicago-house",
        "children",
        "chill",
        "classical",
        "club",
        "comedy",
        "country",
        "dance",
        "dancehall",
        "death-metal",
        "deep-house",
        "detroit-techno",
        "disco",
        "disney",
        "drum-and-bass",
        "dub",
        "dubstep",
        "edm",
        "electro",
        "electronic",
        "emo",
        "folk",
        "forro",
        "french",
        "funk",
        "garage",
        "german",
        "gospel",
        "goth",
        "grindcore",
        "groove",
        "grunge",
        "guitar",
        "happy",
        "hard-rock",
        "hardcore",
        "hardstyle",
        "heavy-metal",
        "hip-hop",
        "holidays",
        "honky-tonk",
        "house",
        "idm",
        "indian",
        "indie",
        "indie-pop",
        "industrial",
        "iranian",
        "j-dance",
        "j-idol",
        "j-pop",
        "j-rock",
        "jazz",
        "k-pop",
        "kids",
        "latin",
        "latino",
        "malay",
        "mandopop",
        "metal",
        "metal-misc",
        "metalcore",
        "minimal-techno",
        "movies",
        "mpb",
        "new-age",
        "new-release",
        "opera",
        "pagode",
        "party",
        "philippines-opm",
        "piano",
        "pop",
        "pop-film",
        "post-dubstep",
        "power-pop",
        "progressive-house",
        "psych-rock",
        "punk",
        "punk-rock",
        "r-n-b",
        "rainy-day",
        "reggae",
        "reggaeton",
        "road-trip",
        "rock",
        "rock-n-roll",
        "rockabilly",
        "romance",
        "sad",
        "salsa",
        "samba",
        "sertanejo",
        "show-tunes",
        "singer-songwriter",
        "ska",
        "sleep",
        "songwriter",
        "soul",
        "soundtracks",
        "spanish",
        "study",
        "summer",
        "swedish",
        "synth-pop",
        "tango",
        "techno",
        "trance",
        "trip-hop",
        "turkish",
        "work-out",
        "world-music",
      ],
    },
    // seed_tracks: {
    //   type: "array",
    //   items: {
    //     type: "string",
    //   },
    //   minItems: 1,
    //   maxItems: 5,
    //   description: "最大5つのSpotify曲ID。",
    // },
    min_acousticness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲の最小アコースティック値。",
    },
    max_acousticness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲の最大アコースティック値。",
    },

    min_danceability: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲のダンスに適した曲かのパラメータの最小値。",
    },
    max_danceability: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲のダンスに適した曲かのパラメータの最大値。",
    },

    // min_duration_ms: {
    //   type: "integer",
    //   minimum: 0,
    //   description: "レコメンドする曲の最小長さ（ミリ秒）。",
    // },
    // max_duration_ms: {
    //   type: "integer",
    //   minimum: 0,
    //   description: "レコメンドする曲の最大長さ（ミリ秒）。",
    // },

    min_energy: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲がエネルギッシュかの最小値。",
    },
    max_energy: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲がエネルギッシュかの最大値。",
    },

    min_instrumentalness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲のボーカルがいる時間の最小値。",
    },
    max_instrumentalness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲のボーカルがいる時間の最大値。",
    },

    min_key: {
      type: "integer",
      minimum: 0,
      maximum: 11,
      description: "レコメンドする曲のキーの最小値（音階）。",
    },
    max_key: {
      type: "integer",
      minimum: 0,
      maximum: 11,
      description: "レコメンドする曲のキーの最大値（音階）。",
    },

    // min_liveness: {
    //   type: "number",
    //   minimum: 0,
    //   maximum: 1,
    //   description: "レコメンドする曲の最小ライブネス値。",
    // },
    // max_liveness: {
    //   type: "number",
    //   minimum: 0,
    //   maximum: 1,
    //   description: "レコメンドする曲の最大ライブネス値。",
    // },

    // min_loudness: {
    //   type: "number",
    //   description: "レコメンドする曲の最小ラウドネス値。",
    // },
    // max_loudness: {
    //   type: "number",
    //   description: "レコメンドする曲の最大ラウドネス値。",
    // },

    min_mode: {
      type: "integer",
      minimum: 0,
      maximum: 1,
      description:
        "レコメンドする曲がメジャーかどうかの最小値。0はマイナー、1はメジャーを示します。",
    },
    max_mode: {
      type: "integer",
      minimum: 0,
      maximum: 1,
      description:
        "レコメンドする曲がメジャーかどうかの最大値。0はマイナー、1はメジャーを示します。",
    },

    min_speechiness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲に話し言葉が含まれているかどうかの最小値",
    },
    max_speechiness: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "レコメンドする曲に話し言葉が含まれているかどうかの最大値",
    },

    min_tempo: {
      type: "number",
      minimum: 0,
      description: "レコメンドする曲のテンポの最小値（BPM）。",
    },
    max_tempo: {
      type: "number",
      minimum: 0,
      description: "レコメンドする曲のテンポの最大値（BPM）。",
    },

    min_time_signature: {
      type: "integer",
      minimum: 0,
      description: "レコメンドする曲の1小節あたりの拍数の最小値。",
    },
    max_time_signature: {
      type: "integer",
      minimum: 0,
      description: "レコメンドする曲の1小節あたりの拍数の最大値。",
    },

    min_valence: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description:
        "曲が陽性の感情（例えば、幸せ、楽観的、陽気）を伝える確率の最小値",
    },
    max_valence: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description:
        "曲が陽性の感情（例えば、幸せ、楽観的、陽気）を伝える確率の最大値",
    },
  },
  required: [
    "min_acousticness",
    "max_acousticness",
    "min_danceability",
    "max_danceability",
    "min_energy",
    "max_energy",
    "min_instrumentalness",
    "max_instrumentalness",
    "min_key",
    "max_key",
    "min_mode",
    "max_mode",
    "min_speechiness",
    "max_speechiness",
    "min_tempo",
    "max_tempo",
    "min_time_signature",
    "max_time_signature",
    "min_valence",
    "max_valence",
  ],
  additionalProperties: false,
};
